### ISSUE TITLE
What happens when there is no object in pool?

### ISSUE THREAD

**Issue by winnieryl** [pomma89/ObjectPool#13]
Hi, 
I am writing a test program using ObjectPool. I set the maxpoolsize to 5, and create 30 threads to borrow objects from the pool. I find that the object constructor is being called more than 5 times(12 times in my case). 
So I want to know what happens when the number of objects in the pool reaches its max size, does it block until other threads returns an object, or it creates a new object? in the later case, when it returns the object and found the pool is full, is it being discard?

Thanks.

**Comment by pomma89** [comment]
Hello @winnieryl ,

When pool is empty, and an object is requested, then the pool creates and returns a new object.

When an object returns to the pool, and the pool is already full, then it is disposed and not added to the pool.

In your test, concurrent threads consume the pool faster than it is refilled: therefore, more objects than necessary are created.

Let me know if you have further questions.

**Comment by winnieryl** [comment]
Hi @pomma89 ,

Thanks for your response, its all clear to me now.
