### ISSUE TITLE
pool grows above max size

### ISSUE THREAD

**Issue by rjm2k** [pomma89/ObjectPool#3]
Thanks for updating the original and adding to nuget, I was very happy to find this, however there is a significant difference between this and the original which defeats the purpose from my point of view.  With the original version the pool did not grow above the maximum size and an attempt to get an object when the pool was fully used would block until an object was freed, your version simply creates a brand new object and returns anyway which makes it an unlimited pool.  I'm not sure if this is a deliberate change in behaviour or accidental?  Also, in the original version, the number of objects specified as the minimum were created up front as the pool was created, this meant that once the pool was established no further construction of object took place, ie we knew that everything was up and running ok, this isn't a huge issue though but the lack of blocking is.

The draw method of the original had this which is where the blocking took place - is there any likelihood that your version will be amended to block when no pool objects are available?

```
                       else
			{
				if (m_canExhaust)
				{
					throw (new InvalidOperationException (S"Pool exhausted!"));
				}
				**else // the pool should wait until a free object returns
				{
					Trace (S"Draw: Waiting for free object to return in the pool");
					while (po == 0)
					{
						po = InternalDraw ();
						Thread::Sleep (0); // give just a scrap of time
					}
					Trace (S"Wait finished. At least one free object returned.");
					return (po);
				} // if (m_canExhaust)**
			} // if (Grow (-1))
```

Many thanks

**Comment by pomma89** [comment]
Hi @rjm2k,

The first issue you point out is that when all objects are out of the pool, and an object is requested, then a new object is created instead of blocking until one old object returns to the pool. However, this behavior was already present in the original version:

```cs
        /// <summary>
        /// Get a monitored object from the pool. 
        /// </summary>
        /// <returns></returns>
        public T GetObject()
        {
            T dequeuedObject = null;

            if (PooledObjects.TryDequeue(out dequeuedObject))
            {
                // Invokes AdjustPoolSize asynchronously
                ThreadPool.QueueUserWorkItem(new WaitCallback((o) => AdjustPoolSizeToBounds()));

                // Diagnostics update
                Diagnostics.IncrementPoolObjectHitCount();

                return dequeuedObject;
            }
            else
            {
                // This should not happen normally, but could be happening when there is stress on the pool
                // No available objects in pool, create a new one and return it to the caller
                Debug.Print("Object pool failed to return a pooled object. pool is empty. consider increasing the number of minimum pooled objects.");

                // Diagnostics update
                Diagnostics.IncrementPoolObjectMissCount();

                return CreatePooledObject();
            }
        }

```

You can double check by following the [first download link](https://www.codeproject.com/KB/cs/535735/GenericObjectPool_OfirMakmal_v1.1.zip) on the [CodeProject article page](https://www.codeproject.com/Articles/535735/Implementing-a-Generic-Object-Pool-in-NET).

In any case, even if more than max pool size objects are created, the size of the pool cannot grow beyond that limit: exceeding objects are simply discarded.

For what concers your second point, that is, when the pool is created the minimum size is not immediately honored, I'll have a look at that as soon as I can, most likely this weekend.

Thanks, have a nice day.

**Comment by pomma89** [comment]
Hi, just released v3 completely removes "minimum pool capacity" in order to improve performance and to avoid the need for multithreading. Please check our benchmarks to see that this version is sometimes 10 times faster than the original pool.

Therefore, I think its better to close this issue.

**Comment by rjm2k** [comment]
thanks, for some reason I thought your project was based on the original from 2002 rather than an updated version   https://www.codeproject.com/Articles/3112/ObjectPool-a-library-for-pooling-NET-objects

my mistake

thanks

**Comment by jgitter** [comment]
Whether this feature was present in a prior version or not, this breaks the library as far as I'm concerned.  The point of a pool of expensive objects is to limit the number of them you have to create.  Not being able to set a maximum means that at load, you may take down your system building a bunch of expensive objects only to ultimately throw them away when they attempt to get added to the pool afterwards.  You could at least provide an alternative ObjectPool implementation which enables this as a feature.  Back to Nuget land to find a proper pool alternative.  : /

**Comment by pomma89** [comment]
Hello @jgitter ,

Of course you can set a maximum limit (e.g. see [this constructor](https://github.com/pomma89/ObjectPool/blob/e94f923fcedde726335661f5b347a59478d6a2df/src/CodeProject.ObjectPool/ObjectPool.cs#L56)). Without that feature, this pool would not make much sense, but of course it has that and other features.

What was removed in v3 was minimum size, which did more harm than good.

Goodbye.

**Comment by pomma89** [comment]
What is not provided is a feature to block creation of new objects when under pressure. This would introduce locking mechanisms which are out of scope of this library and are usually application specific.

Thanks.

**Comment by jgitter** [comment]
I'm not arguing that it's out of scope of this library.  My point is that it shouldn't be out of scope for a pool implementation.  That is the single most necessary and most complicated part of a pool's implementation.  The only way I could add that would be to externally track some sort of Semaphore prior to retrieving the item from the pool.  This would require a host of different event listeners to keep it in sync.  There are pool implementations like Commons.Pool that come with this feature.
